### ISSUE TITLE
Warnings with latest Immutable.js

### ISSUE THREAD

**Issue by mickeyvip** [mgechev/angular-immutable#8]
Hello.

I am following your blog post http://blog.mgechev.com/2015/03/02/immutability-in-angularjs-immutablejs/ and using the latest `immutable.js` - `v3.7.6`.

Running the first example that uses `angular-immutable` brings the following warning:

```
iterable.length has been deprecated, use iterable.size or iterable.count(). This warning will become a silent error in a future version. Error
    at List.Object.defineProperty.get (http://localhost:8080/node_modules/immutable/dist/immutable.js:4650:21)
    at isArrayLike (http://localhost:8080/node_modules/angular/angular.js:282:46)
    at $watchCollectionInterceptor (http://localhost:8080/node_modules/angular/angular.js:16192:22)
    at Object.regularInterceptedExpression (http://localhost:8080/node_modules/angular/angular.js:14949:16)
    at Scope.$digest (http://localhost:8080/node_modules/angular/angular.js:16390:40)
    at Scope.$apply (http://localhost:8080/node_modules/angular/angular.js:16662:24)
    at bootstrapApply (http://localhost:8080/node_modules/angular/angular.js:1679:15)
    at Object.invoke (http://localhost:8080/node_modules/angular/angular.js:4657:17)
    at doBootstrap (http://localhost:8080/node_modules/angular/angular.js:1677:14)
    at Object.bootstrap (http://localhost:8080/node_modules/angular/angular.js:1697:12)
```

Although it's a warning, I wanted to point this out.

Thank you.

**Comment by mickeyvip** [comment]
Seems like it is related to `angular` and not to the directive.
